baseurl: 'https://semenov.example.com' # TODO: заменить после покупки домена
theme: ['hugo-coder-CoW-modifications', 'coder']
title: 'Andrei Semenov'
languageCode: en-US
DefaultContentLanguage: en
author: Andrei Semenov
pagination.pagerSize: 10
enableEmoji: true
enableGitInfo: true
titleCaseStyle: 'firstupper'
canonifyURLs: true

indexes:
  tag: tags
  topic: topics


params:
  author: Andrei V. Semenov
  customCSS: ["css/custom.css"]
  customSCSS: ["scss/custom.scss", "scss/twocol.scss"]
  customJS: ["js/bibtex.js"]
  colorScheme: "auto"
  since: 2025
  keywords: "math,research,complex analysis,functional analysis"
  description: "Personal site of Andrei V. Semenov"
  avatarURL: "images/avatar.jpg"
  favicon_32: "images/favicon-32x32.png"
  favicon_16: "images/favicon-16x16.png"
  touchicon: "images/apple-touch-icon.png"
  manifest: "/site.webmanifest"
  katex: "true"
  math: "true"
  subtitle: mathematician

  social:
    - name: "email"
      icon: "fa fa-2x fa-envelope"
      weight: 1
      url: "mailto:asemenov.spb.56@gmail.com"

    - name: "Telegram"
      icon: "fa fa-2x fa-telegram"
      weight: 2
      url: "https://t.me/Andrei_V_Semenov"

